services:
  # Place here the default dependency injection configuration

  YourVendor\YourExtension\Matomo\ModifyMatomoSiteId:
    tags:
      - name: "event.listener"
        identifier: "your-vendor/your-extension/modify-matomo-site-id"
